import type { Content } from './ar'

/** English copy. Mirrors the Arabic structure key for key; product terms follow the app's English UI. */
export const en: Content = {
  locale: 'en',
  dir: 'ltr',
  brand: {
    name: 'RCH',
    fullName: 'Rent Clever Helper',
    tagline: 'The smart helper for car rental',
  },
  meta: {
    title: 'RCH — Car rental office management dashboard',
    description: 'RCH (Rent Clever Helper) is a dashboard for running car rental offices: vehicles, contracts, extensions, payments, commissions, office dues and reports — in one place.',
  },
  nav: {
    how: 'How it works',
    features: 'Features',
    about: 'About RCH',
    menu: 'Menu',
    close: 'Close menu',
    home: 'Home',
    skip: 'Skip to content',
    switchTo: 'العربية',
    switchToLang: 'ar',
    primaryNav: 'Main navigation',
  },
  cta: {
    discover: 'Discover Rent Clever Helper',
    contact: 'Contact us',
    start: 'Get started with RCH',
    whatsappMessage: 'Hello, I would like to learn more about RCH for managing a car rental office.',
  },
  hero: {
    eyebrow: 'Car rental office management dashboard',
    titleLines: ['Car rental management,', 'made easier with Rent Clever Helper'],
    body: 'Your offices, vehicles, contracts and payments — all in one place.',
    frameLabel: 'Illustrative view of the Rent Clever Helper dashboard',
  },
  problem: {
    eyebrow: 'Before RCH',
    titleLines: ['The office runs…', 'but the information is scattered.'],
    body: 'A contract in an Excel file, a payment in a WhatsApp chat, an extension written in a notebook, and the commission worked out on a calculator. Every day you hunt for the right number in more than one place.',
    scraps: [
      { kind: 'sheet', label: 'Excel', text: 'contracts_sept_FINAL (2).xlsx' },
      { kind: 'chat', label: 'WhatsApp', text: 'Did you send the second payment? 🙏' },
      { kind: 'note', label: 'Notebook', text: '3-day extension — the white Camry' },
      { kind: 'files', label: 'Many files', text: 'Partner office statement — old copy' },
      { kind: 'calc', label: 'Manual math', text: '88 × 10% = ?' },
    ],
    afterEyebrow: 'With RCH',
    afterTitle: 'everything is clearer.',
    afterBody: 'One record for every vehicle, contract and payment — with the numbers already worked out.',
    unifiedLabel: 'One record',
  },
  story: {
    eyebrow: 'How it works',
    title: 'From the vehicle to the report, in one flow',
    progressLabel: 'Stages of work in RCH',
    chapters: [
      {
        id: 'fleet',
        label: 'Fleet',
        title: 'Every vehicle, with its real status',
        body: 'A vehicle’s status updates automatically from its contracts, so you see what’s available and what’s rented at a glance.',
        points: ['Available · Rented · Maintenance · Inactive', '“Rented” is driven by contracts, not set by hand', 'A full movement history for each vehicle'],
      },
      {
        id: 'contracts',
        label: 'Contracts',
        title: 'Clear contracts, no overlaps',
        body: 'Record a fixed-term or an open contract, and follow active, completed and overdue ones in one place.',
        points: ['Fixed-term or open contracts', 'Overdue contracts stand out immediately', 'The same vehicle can’t be rented for overlapping periods'],
      },
      {
        id: 'payments',
        label: 'Extensions & payments',
        title: 'Extend a contract and record a payment in seconds',
        body: 'Each extension is kept in the contract’s history with its amount and date, and every payment shows against what remains.',
        points: ['Full extension history', 'Paid and remaining per contract', 'Track the end date'],
      },
      {
        id: 'calc',
        label: 'Commissions & dues',
        title: 'The numbers come out ready',
        body: 'Revenue, the operator’s commission and each partner office’s due — calculated automatically from the contracts themselves.',
        points: ['The commission rate is saved inside each contract', 'Office due = total − operator commission', 'A general total across all offices'],
      },
      {
        id: 'reports',
        label: 'Reports',
        title: 'Your report, ready whenever you need it',
        body: 'Reports by office and by period, exported to Excel in one click.',
        points: ['Reports by office', 'Reports by period', 'Excel export'],
      },
    ],
    finale: 'Everything in one place.',
  },
  control: {
    eyebrow: 'Features',
    titleLines: ['Every detail of your fleet,', 'under control'],
    body: 'Each vehicle’s contracts on one timeline: no overlaps, open contracts are obvious, extensions stand out, and nothing overdue slips by.',
    today: 'Today',
    timelineLabel: 'Illustrative timeline of vehicle contracts',
    swipeHint: 'Swipe to see more days',
    legend: { completed: 'Completed', active: 'Active', open: 'Active · Open', extension: 'Extension', overdue: 'Overdue' },
    facts: [
      { title: 'No overlaps', body: 'A vehicle can’t be rented twice for the same period — overlapping dates are rejected.' },
      { title: 'Open contracts, clearly', body: 'With no end date, the vehicle stays rented until you close the contract.' },
      { title: 'Nothing overdue slips by', body: 'A contract past its end date shows as “Overdue” everywhere.' },
    ],
  },
  about: {
    eyebrow: 'About RCH',
    titleLines: ['A dashboard by', 'Rowad Technical Solutions'],
    body: 'RCH — Rent Clever Helper, the smart helper for car rental, is a dashboard developed by Rowad Technical Solutions, a technology company building digital solutions for businesses. We designed RCH specifically for car rental offices, so partner offices, vehicles, contracts, payments, commissions and reports are managed in one place — in clear language, with accurate numbers.',
    companyLabel: 'Development & support',
    company: 'Rowad Technical Solutions',
    companyNote: 'We develop the dashboard, keep it updated, and provide direct technical support to its users.',
    supportLabel: 'Technical support',
    principles: [
      { title: 'Built for car rental', body: 'Every screen is built around the office’s daily work: the vehicle, the contract, the payment and the due.' },
      { title: 'Arabic first', body: 'A fully right-to-left Arabic interface, with English support.' },
      { title: 'Support close to you', body: 'Reach the support team directly by phone or WhatsApp.' },
    ],
  },
  final: {
    titleLines: ['Ready to run your office', 'the easier way?'],
    body: 'Message us on WhatsApp and we’ll show you how RCH works for your office.',
    callLabel: 'Or call',
  },
  footer: {
    about: 'RCH — Rent Clever Helper, the smart helper for car rental. One dashboard for offices, partner offices, vehicles, contracts, payments, commissions and reports.',
    navTitle: 'On this page',
    contactTitle: 'Contact',
    support: 'Technical support',
    whatsapp: 'WhatsApp',
    poweredBy: 'Supported and developed by Rowad Technical Solutions',
    rights: 'All rights reserved.',
    sampleNote: 'Interfaces shown on this page are illustrative and use sample data.',
    backToTop: 'Back to top',
  },
  ui: {
    sampleData: 'Sample data',
    currency: 'OMR',
    nav: ['Home', 'Offices', 'Vehicles', 'Rentals', 'Reports', 'Settings'],
    dashboardTitle: 'Overview',
    dashboardSubtitle: 'Vehicles, rentals and offices in one place',
    totalVehicles: 'Total vehicles',
    availableVehicles: 'Available vehicles',
    rentedVehicles: 'Rented vehicles',
    activeRentals: 'Active rentals',
    fleetStatus: 'Fleet status',
    currentRentals: 'Current rentals',
    vehicles: 'Vehicles',
    vehicle: 'Vehicle',
    office: 'Office',
    renter: 'Renter',
    status: 'Status',
    from: 'From',
    to: 'To',
    days: 'Days',
    contractValue: 'Contract value',
    rentalTitle: 'Rental',
    openContract: 'Open contract',
    openContractNoEnd: 'The end date is set when the contract is closed.',
    newRental: 'New rental',
    conflict: 'This vehicle is rented to Salem Al-Harthi from 12/10 to 18/10. Choose dates that don’t overlap.',
    extensionsTitle: 'Extension details',
    originalAmount: 'Original amount',
    extensionFirst: 'First extension',
    extensionSecond: 'Second extension',
    amountAfterExtension: 'Amount after extension',
    payment: 'Payment',
    paid: 'Paid',
    remaining: 'Remaining',
    paymentRecorded: 'Payment recorded',
    endsIn: 'Ends in 3 days',
    generalTotal: 'General total',
    operatorCommission: 'Operator commission',
    partnerDue: 'Office due',
    partnerOffices: 'Partner offices',
    commissionRate: 'Commission rate',
    reportsTitle: 'Reports',
    reportsSubtitle: 'Practical reports you can export to Excel',
    filterOffice: 'Office: All',
    filterPeriod: 'This month',
    exportRentals: 'Export rentals',
    exportFile: 'rentals-report.xlsx',
    exported: 'File exported',
    autoUpdated: 'Updated automatically',
    vehicleStatus: { available: 'Available', rented: 'Rented', maintenance: 'Maintenance', inactive: 'Inactive' },
    rentalStatus: { active: 'Active', open: 'Active · Open', completed: 'Completed', overdue: 'Overdue' },
  },
  sample: {
    vehicles: [
      { name: 'Toyota Camry 2024', plate: '4521 AB', office: 'Al Rayyan Office', status: 'rented' },
      { name: 'Hyundai Accent 2023', plate: '7718 KR', office: 'Al Nukhba Office', status: 'available' },
      { name: 'Nissan Patrol 2022', plate: '3390 MS', office: 'Al Rayyan Office', status: 'maintenance' },
      { name: 'Kia Sportage 2024', plate: '6025 HD', office: 'Al Shorouq Office', status: 'rented' },
      { name: 'Toyota Yaris 2021', plate: '1187 TA', office: 'Al Nukhba Office', status: 'inactive' },
    ],
    renters: ['Salem Al-Harthi', 'Mohammed Al-Balushi', 'Khalid Al-Amri', 'Fahad Al-Shehri', 'Nasser Al-Kindi'],
    offices: ['Al Rayyan Office', 'Al Nukhba Office', 'Al Shorouq Office'],
    dates: { start: '12/10', end: '18/10', ext1: '+3 days', ext2: '+2 days' },
  },
}
